services:
  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: duck
      POSTGRES_PASSWORD: duck
      POSTGRES_DB: duck
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
